# Generated by Django 2.2.5 on 2021-03-22 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300, verbose_name='content')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='created_name')),
            ],
        ),
        migrations.CreateModel(
            name='BlogRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars_count', models.IntegerField(default=0, max_length=5, verbose_name='starts_count')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='created_name')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300, verbose_name='content')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='created_name')),
                ('replies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogs.CommentReply')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='the text content of the blog as an html text', verbose_name='content')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='created_name')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('blog_rates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogRate')),
                ('comments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogComments')),
            ],
        ),
    ]
