# Generated by Django 2.2.5 on 2021-03-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='blograte',
            name='rated_by',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogComments',
        ),
        migrations.DeleteModel(
            name='BlogRate',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
