# Generated by Django 2.2.5 on 2021-03-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogimages',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blograte',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blograte',
            name='rated_by',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='replied_by',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogComments',
        ),
        migrations.DeleteModel(
            name='BlogImages',
        ),
        migrations.DeleteModel(
            name='BlogRate',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
