# Generated by Django 2.2.5 on 2021-03-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20210323_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.FileField(default='', upload_to='images/blogs/cover/%y/%m/%d/%h', verbose_name='cover_image'),
        ),
    ]
