# Generated by Django 2.2.5 on 2021-03-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20210323_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Untitled', max_length=100, verbose_name='content'),
        ),
    ]
