# Generated by Django 2.2.5 on 2021-03-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.FileField(upload_to='images/blogs/cover/%y/%m/%d/%h', verbose_name='cover_image'),
        ),
    ]
