# Generated by Django 2.2.5 on 2021-03-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20210327_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.FileField(upload_to='uploads/images/blogs/%y/%m/%d/%h/%M/%s', verbose_name='image'),
        ),
    ]
