# Generated by Django 2.2.5 on 2021-03-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20210327_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='blog_comment_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='blogimages',
            name='blog_image_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='blograte',
            name='blog_rate_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='blog_comment_reply_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
