# Generated by Django 2.2.5 on 2021-03-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfos',
        ),
    ]
