# Generated by Django 2.2.5 on 2021-03-12 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0002_delete_userinfos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fallowers', models.ManyToManyField(related_name='fallowers', to=settings.AUTH_USER_MODEL)),
                ('fallowing', models.ManyToManyField(related_name='fallowing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
