# Generated by Django 2.2.5 on 2021-03-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210313_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfos',
        ),
    ]
