# Generated by Django 2.2.5 on 2021-03-13 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0009_delete_userinfos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallowers', models.IntegerField(default=0, help_text='the number of fallowers the user has.')),
                ('fallowing', models.IntegerField(default=0, help_text='the number of users the user is fallowing.')),
                ('stars', models.IntegerField(default=0, help_text='the number of stars the user have gained.')),
                ('profile_img', models.FileField(upload_to='static/profile/img', verbose_name='profile_img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
