# Generated by Django 2.2.5 on 2021-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_userinfos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='profile_img',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='profile_img'),
        ),
    ]
