# Generated by Django 2.2.5 on 2021-03-13 16:24

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20210313_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='profile_img',
            field=models.FileField(default=index.models.default_file, upload_to='uploads/%Y/%m/%d/', verbose_name='profile_img'),
        ),
    ]
