# Generated by Django 2.2.5 on 2021-03-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20210313_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='profile_img',
            field=models.FileField(default='uploads/test.jpg', upload_to='uploads/%Y/%m/%d/', verbose_name='profile_img'),
        ),
    ]
