# Generated by Django 2.2.5 on 2021-03-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_userinfos_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='DjE7yQCFCa0IpAt', max_length=15),
        ),
    ]
