# Generated by Django 2.2.5 on 2021-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_userinfos__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='OifXFrhn5pLThnC', max_length=15),
        ),
    ]
