# Generated by Django 2.2.5 on 2021-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20210314_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='dA0I2eJ1CHUiNB0', max_length=15),
        ),
    ]
