# Generated by Django 2.2.5 on 2021-03-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20210322_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='Q0IdcDWFD6Jd1Tb', max_length=15),
        ),
    ]
