# Generated by Django 2.2.5 on 2021-03-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20210322_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='CFVD6eCqmo4ZDki', max_length=15),
        ),
    ]
