# Generated by Django 2.2.5 on 2021-03-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20210322_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='MQ2d4hQ4MZe2Xom', max_length=15),
        ),
    ]
