# Generated by Django 2.2.5 on 2021-03-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20210322_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='7iD0jDalZyoPkG1', max_length=15),
        ),
    ]
