# Generated by Django 2.2.5 on 2021-03-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20210322_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='DoA6DJnonx9CyPZ', max_length=15),
        ),
    ]
