# Generated by Django 2.2.5 on 2021-03-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20210322_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='deTeKgS0jJNPjn4', max_length=15),
        ),
    ]
