# Generated by Django 2.2.5 on 2021-03-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20210322_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='77do7iKEgFbRQmb', max_length=15),
        ),
    ]
