# Generated by Django 2.2.5 on 2021-03-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20210322_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='27oHkJCLO4bLrSw', max_length=15),
        ),
    ]
