# Generated by Django 2.2.5 on 2021-03-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_auto_20210322_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='NDS6L5G0lVSP7iF', max_length=15),
        ),
    ]
