# Generated by Django 2.2.5 on 2021-03-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_auto_20210322_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='wWyjCNh1ncUSiRg', max_length=15),
        ),
    ]
