# Generated by Django 2.2.5 on 2021-03-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_auto_20210323_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='ClQG5Upex6tgZwe', max_length=15),
        ),
    ]
