# Generated by Django 2.2.5 on 2021-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_auto_20210327_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='l5xezakyiD0SJOn', max_length=15),
        ),
    ]
