# Generated by Django 2.2.5 on 2021-03-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_auto_20210327_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='IaCjurvZjUU0mc0', max_length=15),
        ),
    ]
