# Generated by Django 2.2.5 on 2021-03-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_auto_20210327_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='mSWxzzc9fMTEm0u', max_length=15),
        ),
    ]
