# Generated by Django 2.2.5 on 2021-03-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_auto_20210327_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='N92MzdAoShH5xrw', max_length=15),
        ),
    ]
