# Generated by Django 2.2.5 on 2021-03-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_auto_20210327_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='miyFEWQMRgaNOyy', max_length=15),
        ),
    ]
