# Generated by Django 2.2.5 on 2021-03-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_auto_20210327_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='on2UlCxxmXiwc9T', max_length=15),
        ),
    ]
