# Generated by Django 2.2.5 on 2021-03-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_auto_20210327_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='E7eFXVNPZBu3VqS', max_length=15),
        ),
    ]
