# Generated by Django 2.2.5 on 2021-04-15 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_auto_20210328_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfallowers',
            name='fallower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='userfallowing',
            name='fallowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='Zc9nI1mxFJGy8kQ', max_length=15),
        ),
    ]
