# Generated by Django 2.2.5 on 2021-04-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0043_auto_20210415_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='FROTRsiodKNeXuc', max_length=15),
        ),
    ]
