# Generated by Django 2.2.5 on 2021-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0044_auto_20210425_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='CuPFftOAZngo43o', max_length=15),
        ),
    ]
