# Generated by Django 2.2.5 on 2021-06-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0045_auto_20210508_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='FCSyrJw3iZkh12e', max_length=15),
        ),
    ]
