# Generated by Django 2.2.5 on 2021-06-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0046_auto_20210620_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='GJX6temzTfHpFqh', max_length=15),
        ),
    ]
