# Generated by Django 2.2.5 on 2021-06-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0047_auto_20210620_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='2ok1ixETExUW22O', max_length=15),
        ),
    ]
