# Generated by Django 2.2.5 on 2021-06-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0048_auto_20210620_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='dIJm3cb7FEsv4kS', max_length=15),
        ),
    ]
