# Generated by Django 2.2.5 on 2021-06-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0049_auto_20210620_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='Xb2CfxJLqOTiE7m', max_length=15),
        ),
    ]
