# Generated by Django 2.2.5 on 2021-07-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0050_auto_20210620_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='_id',
            field=models.CharField(default='DotZV7VpieLjrrS', max_length=15),
        ),
    ]
